Blog/urls.py
from django.urls import path
from .views import Total_Post_View , Detail_Post_View

app_name = "blog"
urlpatterns = [
    path('blogs/' , Total_Post_View.as_view() , name = "total_posts" ) ,
    path('blogs/<int:id>/' , Detail_Post_View.as_view() , name = "detail_post"  ) ,
]

Service/urls.py
from django.urls import path
from .views import Service_View
app_name = "service"

urlpatterns = [
    path('services/' , Service_View.as_view() , name = "services" ) ,

]

account/urls.py
from .views import Register_View , Login_View , Logout_View , Team_View
from django.urls import path
app_name = 'account'


urlpatterns = [
    path('register/' , Register_View.as_view() , name = "register" ) ,
    path('login/', Login_View.as_view(), name="login"),
    path('logout/' , Logout_View.as_view() , name="logout") ,
    path('Team_View/' , Team_View.as_view() , name ="team" ) ,
    path('Team_View/<int:page>/', Team_View.as_view(), name="team"),

]

contactus/urls.py
from django.urls import path
from .views import Contact_Us_View

app_name = "contactus"
urlpatterns = [
    path("contactus/" , Contact_Us_View.as_view() , name = "contactus" )
]

home/urls.py
from django.urls import path  
from .views import Home 
app_name = "home"

urlpatterns = [
	path('' , Home.as_view() , name = 'home'  ) , 

]

projects/urls.py
from django.urls import path
from .views import Total_Project_View , Detail_Project_View

app_name = "projects"
urlpatterns = [
    path('projects/' , Total_Project_View.as_view() , name="total_projects" ) ,
    path('projects/<int:page>', Total_Project_View.as_view(), name="total_projects"),

    path('detail_project/<int:id>/' , Detail_Project_View.as_view() , name="detail_project")  ,

]

start/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import  static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/' , include('ckeditor_uploader.urls')) ,
    path('' , include('account.urls') ) ,
    path('' , include('home.urls')) ,
    path('' , include('Blog.urls')) ,
    path('' , include('Service.urls')) ,
    path('' , include('contactus.urls')) ,
    path('' , include('company_customers.urls')) ,
    path('' , include('projects.urls')) ,

]

if settings.DEBUG :
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Blog/models.py
from django.db import models
from account.models import My_Team , Personality_Information
from ckeditor.fields import RichTextField
from django.utils import timezone
from django_jalali.db import models as jmodels
from django.urls import reverse

# Create your models here.


class Category(models.Model) :

    name = models.CharField(verbose_name="عنوان دسته بندی" , max_length=100 )
    slug = models.SlugField(verbose_name="ادرس اینترنتی دسته بندی" , help_text="این فیلد به طور خودکار مقدار دهی میشود" , unique=True )


    def __str__(self):
        return self.name

    class Meta :
        db_table = "Category"
        verbose_name_plural  = "دسته بندی های مقالات"


class Tags(models.Model) :
    name = models.CharField(verbose_name="تگ های مقالات" , max_length=100 )
    slug = models.SlugField(verbose_name="آدرس اینترنتی تگ های مقالات" , unique=True , help_text="به طور خودکار مقدار دهی میشود")

    def __str__(self):
        return self.name

    class Meta :
        db_table = "Tags"
        verbose_name_plural = "تگ های مقالات"



class Post(models.Model) :
    STATUS_CHOICES = (
        ('public' , 'منتشر بشود :)') ,
        ('draft' , 'منتشر نشود :(')
    )

    author = models.ForeignKey(My_Team , verbose_name='عضو تیم ' , on_delete=models.CASCADE )
    picture = models.FileField(verbose_name='تصویر مقاله' , upload_to='Post_Pictures/')
    title  = models.CharField(verbose_name= "عنوان " , max_length= 100 )
    summary = models.CharField(verbose_name="خلاصه متن مروری در 30 کلمه"  , help_text="لطفا به طوری مروری نوشته شود" , max_length=50 , null = True )
    category_this_post = models.ForeignKey(Category , on_delete=models.CASCADE , verbose_name="دسته بندی موضوع" , help_text='این فیلد از قسمت دسته بندی ها انتخاب میشود')
    tags = models.ManyToManyField(Tags ,verbose_name="تگ های مقالات"  , help_text='از قسمت تگ های مقالات ُ این فیلد مقدار دهی میشود')
    text = RichTextField(verbose_name="متن مقاله")
    text2 = RichTextField(verbose_name="متن ۲ در صورت وجود داشتن لازم " , null = True , blank = True )
    time = jmodels.jDateTimeField(verbose_name="زمان ساخت" , auto_now_add= timezone.now  )
    edited = jmodels.jDateTimeField(verbose_name= "زمان ویرایش" , auto_now=True )
    status = models.CharField(verbose_name= 'وضعیت انتشار چگونه باشد ؟ ' , max_length=20 , choices=STATUS_CHOICES , null = True )
    time_read_duration = models.IntegerField(verbose_name="مدت زمان تخمینی مطالعه مقاله" , null=True )

    def __str__(self):
        return self.title

    class Meta :
        db_table = 'Post'
        verbose_name_plural = 'مقالات وبسایت'


    def get_absolute_url(self) :
        return reverse("blog:detail_post" , args=[str(self.id)])



class Comments_Post(models.Model) :
    post   = models.ForeignKey( Post ,  verbose_name='انتخاب مقاله مورد نظر' , on_delete=models.CASCADE )
    name   = models.CharField(verbose_name='نام نظر دهنده' , max_length=100 )
    email  = models.EmailField(verbose_name= 'ایمیل نظر دهنده' )
    text   = models.TextField(verbose_name='متن نظر مخاطب' )
    time   = models.DateTimeField(verbose_name="زمان ارسال نظر"  , auto_now_add= True )


    def __str__(self):
        return f'{self.post} - {self.email}'


    class Meta :
        db_table = "Comments_Post"
        verbose_name_plural = "کامنت های مخاطبین"

Service/models.py
from django.db import models
from ckeditor.fields import RichTextField
# Create your models here.


class Service_Information(models.Model) :

    name      = models.CharField(verbose_name= "اسم خدمت" , max_length=100 )
    picture   = models.FileField(verbose_name='تصویر خدمت' , upload_to='service_picture/' )
    picture2  = models.FileField(verbose_name="تصویر خدمت ۲" , upload_to='service_picture/' , null = True )
    introduce = models.CharField(verbose_name="معرفی نامه خدمت" , max_length= 100 , null=True )
    text      = RichTextField(verbose_name="متن توضیحات" )


    def __str__(self):
        return self.name

    class Meta :
        db_table = "Service_Information"
        verbose_name_plural = "خدمات شرکت مکا "

projects/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.urls import reverse
# Create your models here.
class Project_information(models.Model) :
    picture = models.FileField(verbose_name="تصویر " , upload_to="project_picture/" )
    title   = models.CharField(verbose_name="عنوان " , max_length=100 )
    text    = RichTextField(verbose_name="متن ۱ ")
    texhnology   = models.CharField(verbose_name= "فناوری ها " , help_text="لطفا با ویرگول از هم جدا کنید " , max_length=100 )
    time         = models.CharField(verbose_name="زمان " )
    team_support = models.CharField(verbose_name= "عنوان تیم کمک کننده" , max_length=100 )


    def get_absolute_url(self):
        return reverse('projects:detail_project' , args=[str(self.id)])


    def __str__(self):
        return self.title

    class Meta :
        db_table = "Project_information"
        verbose_name_plural = "پروژه های تیم مکا"

Blog/forms.py
from django import forms
from .models import Comments_Post

class CommentForm(forms.ModelForm) :

    class Meta :
        model = Comments_Post
        fields = ['name' , 'email' , 'text']

Blog/views.py
from django.shortcuts import render
from account.models import Personality_Information
from .models import  Post , Category , Tags , Comments_Post
from django.views import View
from .forms import CommentForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
# Create your views here.

class Total_Post_View(View) :

    def setup(self, request, *args, **kwargs):
        self.posts = Post.objects.filter(status = 'public' )
        self.categories = Category.objects.all()
        self.total_tags = Tags.objects.all()
        self.top_last_post = Post.objects.filter(status = 'public' ).order_by('-time')[:3]
        return super().setup(request , *args , **kwargs )

    def get(self , request ) :
        return render(request , 'front/blog.html' , {'top_last_post':self.top_last_post , 'tags':self.total_tags , 'categories' : self.categories , 'posts' : self.posts})

    def post(self , request ) :
        return render(request , 'front/blog.html' , { 'top_last_post':self.top_last_post , 'tags':self.total_tags  ,'categories' : self.categories  , 'posts' : self.posts})


class Detail_Post_View(View) :

    def setup(self , request , *args , **kwargs   )  :
        self.select_post = Post.objects.get(id = kwargs['id'])
        self.categories = Category.objects.all()
        self.total_tags = Tags.objects.all()
        self.comment_form = CommentForm
        self.top_last_post = Post.objects.filter(status = 'public' ).order_by('-time')[:3]

        return super().setup(request , *args , **kwargs )

    def get(self , request , id )  :
        form = self.comment_form()
        return render(request , 'front/blog-details.html' , { 'top_last_post':self.top_last_post , 'tags':self.total_tags , 'form' :form , 'categories' : self.categories  , 'post' : self.select_post })
    @method_decorator(login_required(login_url = 'account:login'))
    def post(self , request , id ):
        form = self.comment_form(request.POST)
        if form.is_valid() :
            comment = Comments_Post(post = self.select_post , name = form.cleaned_data['name'] ,
                          email  = form.cleaned_data['email'] ,
                          text = form.cleaned_data['text'] )
            comment.save()
            messages.success(request , 'متن شما با موفقیت ثبت شد' , 'success')

        else :
            messages.error(request , 'مشکلی در ثبت وجود دارد ' , 'error')
        return render(request , 'front/blog-details.html' , { 'top_last_post':self.top_last_post , 'tags':self.total_tags , 'form' : form , 'categories' : self.categories   , 'post' : self.select_post })

Service/views.py
from django.shortcuts import render
from django.views import View
from .models import Service_Information
# Create your views here.


class Service_View(View) :

    template_name  = 'front/services.html'

    def setup(self, request, *args, **kwargs):
        self.services = Service_Information.objects.all()
        return super().setup(request , *args , **kwargs )

    def get(self , request ) :
        return render(request , self.template_name , {'services' : self.services })

    def post(self , request ) :
        return render(request , self.template_name , {'services' : self.services })

projects/views.py
from django.shortcuts import render

# Create your views here.
from .models import Project_information
from django.views import View
from django.core.paginator import  Paginator , PageNotAnInteger , EmptyPage

class Total_Project_View(View) :


    template_name = "front/projects.html"
    def setup(self, request, *args, **kwargs):
        self.projects = Project_information.objects.all()

        return super().setup(request , *args , **kwargs )


    def get(self , request , page = 1 ) :
        try :
            paginator = Paginator(self.projects , 2 )
            projects  = paginator.page(page)
        except PageNotAnInteger :
            projects = paginator.page(1)
        except EmptyPage :
            projects = paginator.page(paginator.num_pages)
        return render(request , self.template_name , {

            'projects' : projects ,
        })


    def post(self , request , page =1  ) :
        try :
            paginator = Paginator(self.projects , 2 )
            projects  = paginator.page(page)
        except PageNotAnInteger :
            projects = paginator.page(1)
        except EmptyPage :
            projects = paginator.page(paginator.num_pages)
        return render(request , self.template_name , {

            'projects' : projects ,
        })



class Detail_Project_View(View) :


    template_name = "front/project-details.html"

    def setup(self , request  , *args , **kwargs ) :
        self.detail_project = Project_information.objects.get(id = kwargs['id'] )

        return super().setup(request , *args , **kwargs )


    def get(self , request  , id  ) :

        return render(request , self.template_name , {

        })


    def post(self , request , id ) :
        return render(request , self.template_name , {

        })

templates/front/messages.html
{% block messages %}
{% if messages %}
    {% for msg in messages %}
        <div style="margin-top: 75px" class="alert alert-primary" role="alert">
            {{ msg }}
        </div>
    {% endfor %}
{% endif %}
{% endblock messages %}

templates/front/navbar.html
{% load static  %}
{% block navbar %}
        <nav  class="wile-navbar style navbar navbar-expand-lg navbar-light">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'home:home'  %}">
                    <img width="50px" height="50px" src="{% static 'front/assets/images/logo1.png' %}" alt="Logo">
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item active dropdown">
                            <a class="nav-link dropdown-toggle active" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">صفحه اصلی</a>

                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li>
                                    <a class="dropdown-item active" href="{% url 'home:home' %}">نسخه ی نمایشی خانه </a>
                                </li>

                            </ul>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownPages" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">صفحات</a>
                            
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdownPages">
                                <li>
                                    <a class="dropdown-item" href="#">درباره ما</a>
                                </li>
                                <li>
                                    <a class="dropdown-item" href="#">گواهینامه ها</a>
                                </li>
                                <li>
                                    <a class="dropdown-item" href="{% url 'account:team'  %}">تیم</a>
                                </li>
                                {% if user.is_authenticated %}
                                <li>
                                    <a class="dropdown-item" href="{% url 'account:logout'  %}"> خروج</a>
                                </li>
                                {% else %}
                                    <li>
                                        <a class="dropdown-item" href="{% url 'account:login'  %}"> ورود</a>
                                    </li>
                                    <li>
                                        <a class="dropdown-item" href="{% url 'account:register'  %}">ثبت نام</a>
                                    
                                {% endif %}
                            </ul>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownCourses" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">پروژه ها</a>

                            <ul class="dropdown-menu" aria-labelledby="navbarDropdownCourses">
                                <li>
                                    <a class="dropdown-item" href="{% url 'projects:total_projects'  %}">پروژه ها</a>
                                </li>

                            </ul>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownCourses" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">خدمات</a>

                            <ul class="dropdown-menu" aria-labelledby="navbarDropdownCourses">
                                <li>
                                    <a class="dropdown-item" href="services.html">خدمات</a>
                                </li>
                                <li>
                                    <a class="dropdown-item" href="service-details.html">جزئیات خدمات</a>
                                </li>
                            </ul>
                        </li>
                        
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownCourses" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">وبلاگ</a>

                            <ul class="dropdown-menu" aria-labelledby="navbarDropdownCourses">
                                <li>
                                    <a class="dropdown-item" href="{% url 'blog:total_posts'  %}">وبلاگ</a>
  
                            </ul>
                        </li>
                        
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'contactus:contactus' %}">با ما تماس بگیرید</a>
                        </li>
                    </ul>

                    <ul class="search-progress">
                        <li class="others-options d-flex align-items-center">
                            <div class="all-time d-flex align-items-center">
                                <a href="tel:1800001658">
                                    <i class="flaticon-telephone-call"></i>
                                </a>
                                <div class="phone">
                                    <span class="make">تماس بگیر</span>
                                    <div class="phone-content">
                                        <a href="tel:834485847324">+8344 85847 324</a>
                                    </div>
                                </div>
                            </div>

                            <div class="menu">
                                <a href="contact.html" class="common-btn">شروع کنید</a>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>

{% endblock navbar %}

templates/front/style_slider.html
				<div class="row">

					<div class="col-md-12">
						<div class="slider-hero">
							<div class="featured-carousel owl-carousel">
								<div class="item">
									<div class="work">
										<div class="img d-flex align-items-center justify-content-center" style="background-image: url(images/slider-1.jpg);">
											<div class="text text-center">
												<h2>Discover New Places</h2>
											</div>
										</div>
									</div>
								</div>
								<div class="item">
									<div class="work">
										<div class="img d-flex align-items-center justify-content-center" style="background-image: url(images/slider-2.jpg);">
											<div class="text text-center">
												<h2>Dream Destination</h2>
											</div>
										</div>
									</div>
								</div>
								<div class="item">
									<div class="work">
										<div class="img d-flex align-items-center justify-content-center" style="background-image: url(images/slider-3.jpg);">
											<div class="text text-center">
												<h2>Travel Exploration</h2>
											</div>
										</div>
									</div>
								</div>
							</div>

							<div class="my-5 text-center">
			          <ul class="thumbnail">
			            <li class="active img"><a href="#"><img src="images/thumb-1.jpg" alt="Image" class="img-fluid"></a></li>
                        {% for i in picture_slider %}
			            <li><a href="#"><img src="{{ i.picture.url }}" alt="Image" class="img-fluid"></a></li>
			            {% endfor %}
                      </ul>
			        </div>
						</div>
					</div>
				</div>

templates/front/team.html
{% load static %}
<!DOCTYPE html>
<html lang="ar" dir="rtl">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- Link Of CSS -->
        <link rel="stylesheet" href="{% static 'front/assets/css/bootstrap.rtl.min.css' %}">
        <link rel="stylesheet" href="{% static 'front/assets/css/swiper-bundle.min.css' %}">
        <link rel="stylesheet" href="{% static 'front/assets/css/boxicon.min.css' %}">
        <link rel="stylesheet" href="{% static 'front/assets/css/flaticon_mycollection.css' %}">
        <link rel="stylesheet" href="{% static 'front/assets/css/scrollCue.css' %}">
        <link rel="stylesheet" href="{% static 'front/assets/css/rtl.css' %}">
        <link rel="stylesheet" href="{% static 'front/assets/css/responsive.css' %}">

        <title>تیم متخصصین ما</title>
        <link rel="icon" type="image/png" href="{% static 'front/assets/images/logo1.png' %}">
    </head>

    <body>
        <!-- Preloader -->

        <!-- Preloader End -->

        <!-- Start Header Area -->
        <div class="header-area">
            <!-- Start Top Header Area -->
            <div class="top-header-area style">
                <div class="container-fluid">
                    <div class="row align-items-center">
                        <div class="col-xl-7 col-lg-7 col-md-8">
                            <div class="top-header-info">
                                <ul>
                                    <li>نشانی:<a href="https://www.google.com/" target="_blank">No. 12, Ribbon Wales  Australia</a>
                                    </li>
                                    <li>به ما ایمیل بزنید:<a href="/cdn-cgi/l/email-protection#5b3f342d326f68696e1b3c363a323775383436"><span class="__cf_email__" data-cfemail="670308110e5354555227000a060e0b4904080a">[ایمیل محافظت شده]</span></a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="col-xl-5 col-lg-5 col-md-4">
                            <div class="top-header-social">
                                <ul>
                                    <li>
                                        <a href="https://www.facebook.com/" target="_blank">
                                            <i class='bx bxl-facebook'></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="https://www.twitter.com/" target="_blank">
                                            <i class='bx bxl-twitter'></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="https://www.instagram.com/" target="_blank">
                                            <i class='bx bxl-instagram'></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="https://www.google.com/" target="_blank">
                                            <i class='bx bxl-google'></i>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Start Top Header Area -->
    
            <!-- Navbar Area Start -->
        {% block navbar %}
        {% include 'front/navbar.html'  %}
        {% endblock navbar  %}
            <div>
        {% block messages %}
        {% include 'front/messages.html'  %}
        {% endblock messages %}
        </div>
            <!-- Navbar Area End -->
        </div>

        <!-- Start Page Banner Area -->
        <div class="page-banner-area">
            <div class="container">
                <div class="page-heading">
                    <h1>تیم</h1>
                    <ul>
                        <li>
                            <a href="{% url 'home:home' %}">صفحه اصلی</a>
                        </li>
                        <li>تیم</li>
                    </ul>
                    <!-- shape -->
                    <img class="page-shape-1 moveVertical" src="{% static 'front/assets/images/shape/page-banner-shape-1.png' %}" alt="image">
                    <img class="page-shape-2 rotate" src="{% static 'front/assets/images/shape/page-banner-shape-2.png' %}" alt="image">
                </div>
            </div>
        </div>
        <!-- End Page Banner Area -->

        <!-- Start Team Area -->
        <div class="team-area pt-100 pb-70">
            <div class="container">
                <div class="row" data-cues="slideInUp" data-duration="900">
                    {% for i in team %}
                    <div class="col-xl-3 col-lg-3 col-md-6">
                        <div class="team-card">
                            <img width="100px" height="100px" src="{{ i.my_team_person.picture.url }}" alt="image">
                            <div class="team-info">
                                <h3>{{ i.my_team_person.first_name }} {{ i.my_team_person.last_name }}</h3>
                                <span>{{ i.introduce }}</span>
                            </div>
                        </div>
                    </div>
                    {% endfor %}

                </div>
            </div>
                  
            <div class="service-pagination">
                <nav aria-label="Page navigation example">
                  <ul class="pagination justify-content-center">
                      {% if team.has_previous %}
                            <li class="page-item ">
                            <a class="page-link" href="{% url 'account:team' team.previous_page_number  %}" tabindex="-1">قبلی</a>
                        </li>
                      {% endif %}

                    {% if team.has_next %}
                    <li class="page-item">
                      <a class="page-link" href="{% url 'account:team' team.next_page_number  %}">بعدی</a>
                    </li>
                  {% endif %}
                  </ul>
                </nav>
            </div>
        </div>
        <!-- End Team Area -->

        <!-- Start Subscribe Area -->
        <div class="subscribe-area" data-cues="fadeIn" data-duration="800">
            <div class="container">
                <div class="subscribe">
                    <div class="row align-items-center">
                        <div class="col-lg-4">
                            <div class="section-heading">
                                <h2>به خبرنامه ما بپیوندید و به روز شوید</h2>
                            </div>
                        </div>
                        <div class="col-lg-8">
                            <form method="POST" action="">
                                {% csrf_token %}
                                <div class="form-group">
                                    <input type="text" name="email" class="form-control" placeholder="ایمیل خود را وارد کنید">
                                    <button type="submit" class="common-btn">اکنون مشترک شوید</button>
                                </div>
                                <img class="newsletter-shape-6" src="{% static 'front/assets/images/shape/newsletter-shape-6.png'%}" alt="image">
                            </form>
                        </div>
                    </div>
                    <img class="newsletter-shape-5" src="{% static 'front/assets/images/shape/newsletter-shape-5.png'%}" alt="image">
                </div>
            </div>
        </div>
        <!-- End Subscribe Area -->

        <!-- Start Footer Area -->
        {% block footer %}
            {% include 'front/footer.html' %}
        {% endblock footer %}
        <!-- End Footer Area -->

        <!-- Start Copy Area -->

        {% block copy_area %}
        {% include 'front/copy_area.html' %}
        {% endblock copy_area %}
        <!-- End Copy Area -->

        <!-- Start Go Top Area -->
        <div class="scrolltop-wrap">
            <a href="#" role="button" aria-label="Scroll to top">
                <div id="scrolltop-arrow">
                    <i class='bx bx-chevrons-up'></i>
                </div> 
            </a>
        </div>
        <!-- End Go Top Area -->

        <!-- Link Of JS -->
        <script data-cfasync="false" src="/cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js"></script><script src="{% static 'front/assets/js/bootstrap.bundle.min.js' %}"></script>
        <script src="{% static 'front/assets/js/swiper-bundle.min.js' %}"></script>
        <script src="{% static 'front/assets/js/scrollCue.min.js' %}"></script>
        <script src="{% static 'front/assets/js/main.js' %}"></script>
    </body>
</html>